all: build_1 build_2 build_3 

build_1:
	echo "--------part 1-------"
	gcc -o appendMeMore appendMeMore.c

build_2:
	echo "----------part 2----------"
	gcc -o part2 part2.c


build_3:
	echo "------------part 3------------"
	gcc -o part3 part3.c
